/**
 * The coordination issue is a projection of the train record.
 *
 * Only the block between the markers belongs to the supervisor; whatever a
 * person writes around it survives every `sync`.
 */
export const BEGIN = "<!-- supervisor:begin -->";
export const END = "<!-- supervisor:end -->";

const STATE_LABELS = {
	done: "done",
	ready: "ready",
	blocked: "blocked",
	"closed-unproven": "closed, not proven",
};

export function renderBlock(train, evaluation) {
	const lines = [
		BEGIN,
		`## Train \`${train.id}\``,
		"",
		`Generated by \`pnpm supervise sync\` from \`supervisor/trains/${train.id}.json\`; edit outside the markers only.`,
		"",
		"| Item | State | Blocked by | Expected evidence |",
		"| ---- | ----- | ---------- | ----------------- |",
	];
	for (const item of evaluation.items) {
		const state = item.state === "done" ? `done (${item.commit.slice(0, 10)})` : STATE_LABELS[item.state];
		const blockedBy = item.blockedBy.map((dependency) => dependency.label).join(", ") || "-";
		lines.push(`| [${item.label}](${item.url}) ${item.title.replace(/\|/g, "\\|")} | ${state} | ${blockedBy} | ${item.expectedEvidence.join("<br>") || "-"} |`);
	}
	if (evaluation.items.length === 0) lines.push("| - | no item linked yet | - | - |");
	lines.push("", `Status: **${train.status}**${train.presentation ? `, presented at ${train.presentation.presentedAt}` : ", not presented"}.`, END);
	return lines.join("\n");
}

/** `body` with the supervisor block replaced, or appended when it has none. */
export function replaceBlock(body, block) {
	const start = body.indexOf(BEGIN);
	const end = body.indexOf(END);
	if (start >= 0 && end > start) return `${body.slice(0, start)}${block}${body.slice(end + END.length)}`;
	return body.trim() ? `${body.replace(/\s+$/, "")}\n\n${block}\n` : `${block}\n`;
}
